---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

Focus on NYC airbnb data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    borough = neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Let's make a scatterplot
autozoom to zoom out 
textlabel: when hoover on the point, showing up 
```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price $", price, "\nRating:", rating)) |>
  plot_ly(x=~lat, y = ~long, color = ~price, text = ~text_label, 
          type = "scatter", mode = "markers", alpha = 0.5)
```

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

Let's make a BAR plot
```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar", color = ~neighbourhood, colors = "viridis")
```




































